# Optional Custom configuartion file for MiniIO

# This file is not used by default. If you want to use it, you need to uncomment the relevant lines in the docker-compose.yml file.

# Example MinIO configuration file
# See https://docs.min.io/docs/minio-server-configuration-guide.html
