# Additional configuration file for MongoDB. This file can be used to set custom configurations for the MongoDB server.

# For example, you can set the bindIp to allow connections from outside the container:
# bindIp:  # -
#   -
# You can also set the port for MongoDB to listen on:
# port: 27017

# For more configuration options, refer to the official MongoDB documentation:
# https://docs.mongodb.com/manual/reference/configuration-options/
